FROM golang:1.19.4 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod tidy

COPY . .
RUN go build -o /webapi ./cmd/webapi
FROM debian:latest
WORKDIR /root/
COPY --from=builder ./webapi .
CMD ["./webapi"]