FROM golang:1.19.4 AS backend-builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod tidy

COPY . .
RUN go build -o /webapi ./cmd/webapi

FROM debian:bullseye-slim

WORKDIR /app
COPY --from=backend-builder /webapi .

CMD ["./webapi"]

#to mount: docker build -f Dockerfile.frontend -t wasa-frontend .

#to run with tester permisses: docker run --rm --user 1000 -p 3000:3000 wasa-backend
