FROM node:lts AS frontend-builder
WORKDIR /app/webui
COPY webui /app/webui
RUN yarn install
RUN yarn run build-prod

FROM nginxinc/nginx-unprivileged:stable
COPY --from=frontend-builder /app/webui/dist /usr/share/nginx/html

#to mount: docker build -f Dockerfile.frontend -t wasa-frontend .

#to run with tester permisses: docker run --rm --user 1000 -p 3000:3000 wasa-backend
