FROM node:lts AS frontend-builder
WORKDIR /app/webui
COPY webui /app/webui
RUN yarn install
RUN yarn run build-prod

FROM nginxinc/nginx-unprivileged:stable
COPY --from=frontend-builder /app/webui/dist /usr/share/nginx/html

#to mount: docker build -f Dockerfile.backend -t wasa-backend .

#to run with tester permisses: docker run --rm --user 1000 -p 80:8080 wasa-frontend
