FROM node:lts AS builder
WORKDIR /app
COPY webui /app/webui
WORKDIR /app/webui

RUN yarn install

RUN npm run build-prod
FROM nginx:latest
#servo i file a nginx
COPY --from=builder /app/webui/dist /usr/share/nginx/html

